Task1: add price increase scheduling
keyssen/test_task pull request #2
Opened 2024-04-18 10:27 UTC by keyssen

2024-04-21 08:21 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "Feature/task1". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-21 08:40 UTC, GUR-ok requested changes

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/annotation/aspect/ExecutionTimeAspect.java
> +        Object result = joinPoint.proceed();
Если joinPoint.proceed(); бросит исключение время замереется?

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/configuration/BatchConfiguration.java
> +public class BatchConfiguration {
Решение через спринг-батч не плходит к данной задаче. Объяснял на лекции.

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/scheduled/OptimizedPreparedStatementSchedule.java
> +@ConditionalOnExpression("'${app.scheduling.enabled}'.equals('true') and '${app.scheduling.optimization}'.equals('true') and '${app.scheduling.preparedStatement}'.equals('true')")
А можно так? @ConditionalOnExpression("${app.scheduling.enabled:false} and ${app.scheduling.optimization:false} and ${app.scheduling.preparedStatement:false}")

2024-04-21 08:40 UTC, GUR-ok commented on src/main/resources/application-prod.yaml
> +    preparedStatement: true
app.scheduling.preparedStatement плохое название.

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/scheduled/OptimizedPreparedStatementSchedule.java
> +//            String selectQuery = "SELECT * FROM product FOR UPDATE";
Раскоментить. Следующую строку убрать

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/scheduled/OptimizedPreparedStatementSchedule.java
> +            BufferedWriter writer = new BufferedWriter(new FileWriter("products.txt"));
BufferedWriter добавить в трай с ресурсами

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/scheduled/OptimizedPreparedStatementSchedule.java
> +            } catch (SQLException | IOException e) {
Код 1 в 1 как другой работе. буду выставлять замечания одни на двоих

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/scheduled/OptimizedPreparedStatementSchedule.java
> +                connection.setAutoCommit(true);
Зачем connection.setAutoCommit(true);?

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/scheduled/OptimizedPreparedStatementSchedule.java
> +                    for (int i = 1; i <= columnCount; i++) {
в приватный метод

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/ProductService.java
> +        product.setLastQuantityChangeDate(LocalDateTime.now());
Не имеет отношение к задаче

2024-04-21 08:40 UTC, GUR-ok commented on src/main/resources/db/changelog/changeset/create-product-table.xml
> +            <column name="last_quantity_change_date" type="timestamp(6)">
Не имеет отношение к задаче

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/scheduled/OptimizedPreparedStatementSchedule.java
> +                ResultSet resultSet = selectStatement.executeQuery();
Не уверен, что selectQuery нужно делать как preparedStatement, тк у него нет параметров и он вызывается 1 раз. Мб сделать просто statement.

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/model/Product.java
> +    @Column(nullable = false, columnDefinition = "numeric(10,2)")
Эти изменения не имеют отношения к задаче. сделать отдельными фиксами в девелоп, потом эту ветку ребейзнуть на девелом или подмержить в нее дев

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/model/Product.java
>  import jakarta.persistence.*;
Не должно быть схлопнутых импортов

2024-04-21 08:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/configuration/ProductItemProcessor.java
> +        double newPrice = currentPrice * (1 + Double.parseDouble(percent) / 100);
BigDecimal сделать отдельным фиксом

2024-04-21 11:46 UTC, keyssen commented on src/main/java/com/task/mediasoft/configuration/BatchConfiguration.java
> +public class BatchConfiguration {
Я понимаю, что не подходит, просто оставил, так как это первое реализованное решение, хоть и не подходящее. В последнем коммите я убрал спринг-батч

2024-04-21 11:52 UTC, keyssen commented on src/main/java/com/task/mediasoft/product/scheduled/OptimizedPreparedStatementSchedule.java
> +@ConditionalOnExpression("'${app.scheduling.enabled}'.equals('true') and '${app.scheduling.optimization}'.equals('true') and '${app.scheduling.preparedStatement}'.equals('true')")
Так можно, я переделал. Просто способ с использованием метода equals является более понятным при первом прочтении, поэтому я бы предпочёл писать именно так

2024-04-26 07:13 UTC, GUR-ok approved these changes

2024-04-26 07:14 UTC, GUR-ok commented
Апрувнул, не забудь сквош )

2024-04-28 19:28 UTC, merged