Task2: add Criteria API and DataJpaTest
keyssen/test_task pull request #4
Opened 2024-04-25 08:15 UTC by keyssen

2024-04-26 09:15 UTC, GUR-ok requested changes

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/controller/ProductController.java
> +    public ResponseEntity<Map<String, Object>> searchProducts(Pageable pageable, @Valid @RequestBody List<SearchCriterial<?>> searchCriteria) {
Почему респонс мапой? давай сделаем отдельный класс

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/controller/ProductController.java
> +            e.printStackTrace();
зачем мы так оборачиваем в трай кетч, у нас же есть exception handler?

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/exception/ErrorDetails.java
> +    /**
Не нужно пожалуйста в мр к задаче вносить правки, не имеющие отношения к задаче. тяжелее смотреть становится

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/model/dto/ProductFilterDto.java
> +public class ProductFilterDto {
Этот класс где-то используется?

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/ProductService.java
> +        final Specification<Product> specification = (root, query, criteriaBuilder) -> {
Можно так оставить, но я бы выделил в отдельный класс public class ProductSpecification implements Specification<Product>

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/CriteriaMethods.java
> +public class CriteriaMethods {
Давай этот класс уберем, а все сделаем в енуме. пример:
```
package com.crudshop.demo.service.search.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum OperationType {

    EQUAL("="),
    GRATER_THAN_OR_EQ(">="),
    LESS_THAN_OR_EQ("<="),
    LIKE("~");

    private final String code;

    OperationType(String code) {
        this.code = code;
    }

    @JsonValue
    public String getCode() {
        return code;
    }

    @JsonCreator
    public static OperationType fromCode(String code) {
        for (OperationType operationType : OperationType.values()) {
            if (operationType.name().equals(code) || operationType.code.equals(code)) {
                return operationType;
            }
        } return null;
    }
}
```

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/CriteriaMethods.java
> +            case "=":
кроме символа должно поддерживаться слово, означающее операцию (по названию енума). см мой пример выше, там ``` if (operationType.name().equals(code) || operationType.code.equals(code))```

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/Criterial/SearchCriterial.java
> +    Predicate equal(Root<Product> root, CriteriaBuilder criteriaBuilder);
не нравится, что все 4 маппинга прям тут в критерии. их нужно инкапсулировать в отдельный класс стратегии (тоже с дженериком, таким же как у SearchCriterial)

2024-04-26 09:15 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/Enums/OperationEnum.java
> +public enum OperationEnum {
тут енумчик сделать, как скинул пример выше

2024-04-26 09:17 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/Criterial/SearchCriterial.java
> +@JsonSubTypes({@JsonSubTypes.Type(value = StringSearchCriterial.class, name = "id"),
для id мб сделать UUIDSearchCriterial?

2024-04-29 17:13 UTC, keyssen commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/Criterial/SearchCriterial.java
> +    Predicate equal(Root<Product> root, CriteriaBuilder criteriaBuilder);
Я переделал с использованием стратегий. Хотел вызывать стратегию и её методы в сервисе, куда прокидывал бы поле по которому нужно выполнить фильтрацию и value, однако передать value не получалось. можете посмотреть в ветке "check/task2". Сейчас у меня используются стратегия. Просто с помощью стратегии реализуются методы SearchCriterial для фильтрации

2024-05-01 09:24 UTC, GUR-ok requested changes

2024-05-01 09:24 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/ProductSpecification.java
> +        return null;
так а чего тут логики нет? тогда вынеси сюда логкиу из сервиса

2024-05-01 09:25 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/Criterial/SearchCriterial.java
> +    Predicate equal(Root<Product> root, CriteriaBuilder criteriaBuilder);
У менят вот такая кастомная спецификация
```
package com.crudshop.demo.service.search;

import com.crudshop.demo.entity.ProductEntity;
import com.crudshop.demo.service.search.criteria.SearchCriteria;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;
import lombok.RequiredArgsConstructor;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.lang.NonNull;

import java.util.List;

@RequiredArgsConstructor
@SuppressWarnings({"rawtypes", "unchecked"})
public class ProductSpecification implements Specification<ProductEntity> {

    private final List<SearchCriteria> criteriaList;

    @Override
    public Predicate toPredicate(
            @NonNull Root<ProductEntity> root,
            @NonNull CriteriaQuery<?> query,
            @NonNull CriteriaBuilder cb
    ) {
        final List<Predicate> predicates = criteriaList.stream().map(
                it -> {
                    switch (it.getOperation()) {
                        case EQUAL -> {
                            return it.getStrategy().getEqPattern(
                                    root.get(it.getField()),
                                    it.getValue(),
                                    cb
                            );
                        }
                        case GRATER_THAN_OR_EQ -> {
                            return it.getStrategy().getLeftLimitPattern(
                                    root.get(it.getField()),
                                    it.getValue(),
                                    cb
                            );
                        }
                        case LESS_THAN_OR_EQ -> {
                            return it.getStrategy().getRightLimitPattern(
                                    root.get(it.getField()),
                                    it.getValue(),
                                    cb
                            );
                        }
                        case LIKE -> {
                            return it.getStrategy().getLikePattern(
                                    root.get(it.getField()),
                                    it.getValue(),
                                    cb
                            );
                        }
                        default -> throw new IllegalStateException("Unexpected value: " + it.getOperation());
                    }
                }
        ).toList();

        return cb.and(predicates.toArray(new Predicate[0]));
    }
}
```

В сервисе вызывается так:
```
    @Override
    @MeasureExecutionTime
    @SuppressWarnings("rawtypes")
    public List<ProductDto> searchProducts(final Pageable pageable, final List<SearchCriteria> criteriaList) {
        final ProductSpecification spec = new ProductSpecification(criteriaList);
        final Page<ProductEntity> products = productRepository.findAll(spec, pageable);

        return products.stream()
                .map(productEntity -> ProductDto.builder()
                        .id(productEntity.getId())
                        .article(productEntity.getArticle())
                        .name(productEntity.getName())
                        .description(productEntity.getDescription())
                        .categoryType(productEntity.getCategoryType())
                        .price(productEntity.getPrice())
                        .quantity(productEntity.getQuantity())
                        .isAvailable(productEntity.getIsAvailable())
                        .lastQuantityChange(productEntity.getLastQuantityChange())
                        .createdAt(productEntity.getCreatedAt())
                        .build())
                .collect(Collectors.toList());
    }
```

2024-05-01 09:28 UTC, GUR-ok requested changes

2024-05-01 09:28 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/Predicate/PredicateStrategy.java
> +
оставляй по одной пустой строке

2024-05-01 09:28 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/Predicate/PredicateStrategy.java
> +
перед скобкой пустая строка не нужна

2024-05-01 09:28 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/product/service/searchCriteria/Criterial/StringSearchCriterial.java
> +    public Predicate equal(Expression<String> expression, CriteriaBuilder criteriaBuilder) {
тут нужно оставить только геттер для стратегии. геттеры предикатов убирай. Далее поправь по примеру кода, который скинул: в сервисе создавай через конструктор кастомную спецификацию (преедавая туда лист критериев). в кастомной спецификации дергай стратегии. пример кода есть тут в замечаниях

2024-05-04 10:57 UTC, GUR-ok approved these changes

2024-05-04 10:57 UTC, GUR-ok commented
можно мержить со сквошем

2024-05-04 11:04 UTC, merged