Task4: add customer and order entities
keyssen/test_task pull request #6
Opened 2024-05-09 09:26 UTC by keyssen

2024-05-09 09:28 UTC, keyssen commented
![image_2024-05-09_13-27-11](https://github.com/keyssen/mediasoft_test_task/assets/90594135/a4d67ee2-4b2e-43a4-859c-67e82daff410)

2024-05-11 12:35 UTC, GUR-ok requested changes

2024-05-11 12:35 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/controller/OrderController.java
> +    public ViewOrderWithProductDTO getOrderById(@PathVariable UUID id) {
почему тут везде ViewOrderWithProductDTO?

2024-05-11 12:35 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +public class OrderService {
Сделать интерфейс, а это будет реализацией

2024-05-11 12:35 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +    public Order getOrderById(UUID id) {
почему этот метод публичный?

2024-05-11 12:35 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/model/Order.java
> +    public Order(SaveOrderDTO saveOrderDTO) {
убрать этот метод

2024-05-11 12:35 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/model/Order.java
> +    public void addToOrderProducts(OrderProduct orderProduct) {
и этот убрать

2024-05-11 12:35 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +        final Product currentProduct = productService.getProductById(productId);
Я все это видел. см. https://github.com/amayash/DemoTaskMediasoft/pull/9

2024-05-11 12:35 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +        if (!currentOrder.getCustomer().getId().equals(customerIdProvider.getCustomerId())) {
здесь кстати не нужно проверять на кастомера. метод сервисный. там customerId Не приходит

2024-05-11 12:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +        if (!currentOrder.getCustomer().getId().equals(customerIdProvider.getCustomerId()))
if (!currentOrder.getCustomer().getId().equals(customerIdProvider.getCustomerId()))
            throw new OrderForbiddenCustomerException(customerIdProvider.getCustomerId());
            
            дублируется

2024-05-11 12:40 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +        final Order currentOrder = orderRepository.findById(id)
нам точно нужно дергать весь заказ?

2024-05-11 12:41 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/model/dto/ViewOrderWithProductDTO.java
> +        this.orderId = order.getId();
логики тут быть не должно. считать totalPrice в сервисе

2024-05-11 12:41 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/model/dto/ViewOrderWithProductDTO.java
> +        this.orderId = orderId;
убираем эти конструкторы. логика в сервисе

2024-05-11 12:42 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +
тут бы считать totalPrice а не в конструкторах.

2024-05-11 12:44 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +    public List<ViewProductFromOrderDTO> getAllViewProductsByOrderId(UUID id) {
модель ответа по тз другая. может тут сразу вернем ViewOrderDto?

2024-05-11 12:44 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +                    final OrderProduct currentOrderProduct = orderProductRepository.findOrderProduct(currentOrder.getId(), productId);
orderProductRepository.findOrderProduct вызывается многократно. зачем,е сли мы дергаем  final Order currentOrder = getOrderById(orderId); и там можно сразу подтянуть вложенную коллекцию через join fetch

2024-05-11 12:49 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +                        currentOrder.addToOrderProducts(createOrderProduct(currentOrder, productId, totalQuantity));
createOrderProduct(currentOrder, productId, totalQuantity) идет в бд с селектом. несколько раз, если мы добавляем несколько товаров. нужно 1 раз.
```
2. Находим все товары из запроса по айди одним селектом через findByIdIn, делаем из этого хэшмапу productId -> productEntity
3. Получаем предварительно orderEntity, чтобы его сеттить в orderedProduct
4. По данным товаров из запроса проходимся стримом и собираем новый OrderedProduct или апдейтим кол-во на старом, используя хэшмапу из шага два. Тут же проверяем количество и isAvailable
5. Сеттим в ордер эти товары. и сохраняемся
```

2024-05-11 12:50 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderService.java
> +                        currentOrder.addToOrderProducts(createOrderProduct(currentOrder, productId, totalQuantity))
createOrderProduct(currentOrder, productId, totalQuantity) идет в бд с селектом. несколько раз, если мы добавляем несколько товаров. нужно 1 раз.

2024-05-20 09:27 UTC, GUR-ok approved these changes
Давай помержим со сквошем

2024-05-22 17:45 UTC, merged