Task5: complex logic and k8s
keyssen/test_task pull request #7
Opened 2024-05-22 18:07 UTC by keyssen

2024-05-24 18:20 UTC, keyssen commented
![image](https://github.com/keyssen/mediasoft_test_task/assets/90594135/6f061beb-6580-4d75-a849-7b6701e760e7)

2024-06-01 08:32 UTC, GUR-ok requested changes

2024-06-01 08:32 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/configuration/WebClientConfig.java
> -    public WebClient webClient(WebClient.Builder webClientBuilder) {
Почему все удалил? Сделай тут разные бины WebClient с базовым урлом. Будет три штуки.. или четыре. currencyServiceWebClient, userServiceWebClient, 
crmServiceWebClient, accountServiceWebClient. Инжектить их можно будет без квалифаера, определяя как поле private final WebClient crmServiceWebClient; 
Спринг будет понимать какую именно реализацию инжектить по названию проперти (название проперти должно соответствовать названию метода,
 где бин собирается тут)

2024-06-01 08:32 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderServiceImpl.java
> +            Map<String, String> inns = innsFuture.get();
лучше не get а join (уйдет checked ex и catch блок). плюс я бы наверно не выносил в отдельные переменные, а просто вызывал join на 120 и 122 строке внутри стрима где ты обращаешься к этой коллекции

2024-06-01 08:32 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/order/service/OrderServiceImpl.java
> +                    .collect(Collectors.groupingBy(OrderProduct::getProduct))
тут два стрима друг за другом. можно одним стримом. пример
```
        var map = orders.stream()
                .flatMap(ord -> ord.getProds().stream().map(it -> new AbstractMap.SimpleEntry<Prod, Ord>(it, ord)))
                .collect(
                        Collectors.groupingBy(
                                it -> it.getKey().getName(),
                                Collectors.mapping(
                                        it -> it.getValue().getUuid(),
                                        Collectors.toList()
                                )
                        )
                );
```

2024-06-01 08:32 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/restService/accountService/AccountServiceImpl.java
> +    private final WebClient webClient;
верни configuration, а тут инжекти конкретную реализацию, называя проперти так же как и метод помеченный аннотацией bean

2024-06-01 08:32 UTC, GUR-ok commented on src/main/java/com/task/mediasoft/restService/crmService/CrmServiceClientMock.java
> +        new Thread(() -> {
CompletableFuture.supplyAsync вместо new Thread и start

2024-06-08 09:04 UTC, GUR-ok approved these changes
Давай подмержим со сквошем

2024-06-09 07:25 UTC, merged